import ipdb

combined_dict = {0: {'proper_noun': {'Chinese': 'DDR Ratio',
                                     'German': 'DDR Ratio',
                                     'English': 'DDR Ratio',
                                     'Japanese': 'DDR Ratio'},
                     'description': {'Chinese': 'Defective Dies Ratio,為wafer defect的一個指標，為一個基準定義此批產品是否會報廢，而這些defect影響產品yield的程度。',
                                     'German': 'Defective Dies Ratio: Ein Indikator für Wafer-Defekte, der bestimmt, ob ein Produktbatch verworfen wird. Diese Defekte beeinflussen die Ausbeute des Produkts.',
                                     'English': 'The Defective Dies Ratio is an indicator of wafer defects and serves as a benchmark to determine whether a batch of products will be scrapped. These defects affect the product yield.',
                                     'Japanese': '不良ダイ比率: ウェーハの不良の指標であり、この基準で製品の廃棄を判断します。これらの不良は製品の歩留まりに影響を与えます。'}},
                 1: {'proper_noun': {'Chinese': 'EC',
                                     'German': 'EC',
                                     'English': 'EC',
                                     'Japanese': 'EC'},
                     'description': {'Chinese': '是機台的設定值，有些能修改，因製程調機參數不同可作變動，根據製程定義，有些無法修改，像是機台的溫度都是固定的。機台交回去之前一定要檢查EC是否match母版。',
                                     'German': 'Maschineneinstellungen: Einige Parameter sind anpassbar, abhängig von den Prozessanforderungen. Einige, wie die Temperatur, sind jedoch festgelegt. Vor der Rückgabe der Maschine muss überprüft werden, ob die EC mit der Vorlage übereinstimmt.',
                                     'English': "These are the machine's set values; some can be adjusted based on different process tuning parameters. According to process definitions, certain values, like machine temperature, are fixed and cannot be changed. Before returning the machine, ensure the EC matches the master version.",
                                     'Japanese': '設備の設定値: 一部はプロセスに応じて変更可能ですが、例えば温度などの固定値は変更できません。設備を返却する前に、ECがマスターと一致しているか必ず確認してください。'}},
                 2: {'proper_noun': {'Chinese': 'ECS',
                                     'German': 'ECS',
                                     'English': 'ECS',
                                     'Japanese': 'ECS'},
                     'description': {'Chinese': 'Equipment Constant System. 防止因機台參數被更改而造成產品報廢之風險，相當於設備工程師的RMS。',
                                     'German': 'Equipment Constant System: Verhindert das Risiko von Produktausschuss durch geänderte Maschinenparameter, ähnlich dem RMS eines Anlageningenieurs.',
                                     'English': "Equipment Constant System: Prevents the risk of product scrapping due to changes in machine parameters, similar to an equipment engineer's RMS.",
                                     'Japanese': '設備定数システム: 設備パラメータの変更による製品廃棄のリスクを防ぐもので、設備エンジニアのRMSに相当します。'}},
                 3: {'proper_noun': {'Chinese': 'ECCP',
                                     'German': 'ECCP',
                                     'English': 'ECCP',
                                     'Japanese': 'ECCP'},
                     'description': {'Chinese': 'Engineering Change Certification Plan (工程變更驗證計劃)。',
                                     'German': 'Zertifizierungsplan für Konstruktionsänderungen',
                                     'English': 'Engineering Change Certification Plan',
                                     'Japanese': 'エンジニアリング変更認証計画'}},
                 4: {'proper_noun': {'Chinese': 'ECN',
                                     'German': 'ECN',
                                     'English': 'ECN',
                                     'Japanese': 'ECN'},
                     'description': {'Chinese': 'Engineer Change Notice.',
                                     'German': 'Änderungsmitteilung für Ingenieure',
                                     'English': 'Engineer Change Notice.',
                                     'Japanese': 'エンジニア変更通知'}},
                 5: {'proper_noun': {'Chinese': 'Emergency stop',
                                     'German': 'Emergency stop',
                                     'English': 'Emergency stop',
                                     'Japanese': 'Emergency stop'},
                     'description': {'Chinese': '緊急停止。',
                                     'German': 'Not-Aus',
                                     'English': 'Emergency Stop.',
                                     'Japanese': '緊急停止'}},
                 6: {'proper_noun': {'Chinese': 'Alignment mark',
                                     'German': 'Alignment mark',
                                     'English': 'Alignment mark',
                                     'Japanese': 'Alignment mark'},
                     'description': {'Chinese': '機台上用來定義為基準點的標記，通常為從Wafer上選定一個特定(非對稱、無重複性)的位置，好讓機器能夠自動抓取作為基準點。',
                                     'German': 'Markierung für den Referenzpunkt: Ein bestimmter, nicht symmetrischer und nicht wiederholter Punkt auf dem Wafer wird als Referenzpunkt für die Maschine gewählt.',
                                     'English': 'A reference mark on the machine is used as a baseline, typically selecting a specific (asymmetric, non-repetitive) position on the wafer. This allows the machine to automatically capture it as a reference point.',
                                     'Japanese': '基準点のマーキング: ウェーハ上の特定の非対称で重複のない位置を基準点として機械が自動で認識します。'}},
                 7: {'proper_noun': {'Chinese': 'ALP',
                                     'German': 'ALP',
                                     'English': 'ALP',
                                     'Japanese': 'ALP'},
                     'description': {'Chinese': 'Active Load Port ，當機台的兩個Port被Lot塞滿後，第三批貨先行傳至機台旁的ALP，當機台Port上的貨跑完被取走後，ALP上的貨物會藉由ALP的手臂傳至機台上。',
                                     'German': 'Aktiver Ladeport (ALP): Wenn die zwei Ports der Maschine voll sind, wird die dritte Charge zum ALP geleitet. Nach Entleerung der Ports wird die Charge vom ALP zur Maschine transportiert.',
                                     'English': 'Active Load Port (ALP): When both machine ports are filled, a third batch is sent to the ALP next to the machine. Once the machine ports are cleared, the ALP uses its arm to transfer the batch onto the machine.',
                                     'Japanese': 'アクティブロードポート (ALP): 機械の2つのポートが満杯になると、3番目のロットがALPに送られます。ポートの貨物がなくなると、ALPのアームが貨物を機械に運びます。'}},
                 8: {'proper_noun': {'Chinese': 'STB',
                                     'German': 'STB',
                                     'English': 'STB',
                                     'Japanese': 'STB'},
                     'description': {'Chinese': 'Start to Build，wafer下線。',
                                     'German': 'Produktionsstart, Wafer offline',
                                     'English': 'Start to Build: Wafer is offline.',
                                     'Japanese': 'ビルド開始、ウェーハオフライン'}},
                 9: {'proper_noun': {'Chinese': 'STK',
                                     'German': 'STK',
                                     'English': 'STK',
                                     'Japanese': 'STK'},
                     'description': {'Chinese': 'Stocker儲存櫃。',
                                     'German': 'Stocker-Schränke',
                                     'English': 'Storage Cabinet',
                                     'Japanese': 'ストッカー収納キャビネット'}},
                 10: {'proper_noun': {'Chinese': 'Route',
                                      'German': 'Route',
                                      'English': 'Route',
                                      'Japanese': 'Route'},
                      'description': {'Chinese': 'Process flow (途程)。',
                                      'German': 'Prozessablauf',
                                      'English': 'Process Flow',
                                      'Japanese': 'プロセスフロー'}},
                 11: {'proper_noun': {'Chinese': 'Scrap',
                                      'German': 'Scrap',
                                      'English': 'Scrap',
                                      'Japanese': 'Scrap'},
                      'description': {'Chinese': '報廢。',
                                      'German': 'Ausschuss',
                                      'English': 'Scrap',
                                      'Japanese': '廃棄'}},
                 12: {'proper_noun': {'Chinese': 'Sorter',
                                      'German': 'Sorter',
                                      'English': 'Sorter',
                                      'Japanese': 'Sorter'},
                      'description': {'Chinese': '排序機台。',
                                      'German': 'Sortiermaschine',
                                      'English': 'Sorting Machine',
                                      'Japanese': 'ソーティングマシン'}},
                 13: {'proper_noun': {'Chinese': 'Split',
                                      'German': 'Split',
                                      'English': 'Split',
                                      'Japanese': 'Split'},
                      'description': {'Chinese': '分帳、分批。',
                                      'German': 'Konten- und Chargentrennung',
                                      'English': 'Batch and Split Accounting',
                                      'Japanese': '会計分割・バッチ分割'}},
                 14: {'proper_noun': {'Chinese': '大夜',
                                      'German': 'Nachtschicht',
                                      'English': 'night shift',
                                      'Japanese': '夜勤'},
                      'description': {'Chinese': '大夜',
                                      'German': 'Nachtschicht',
                                      'English': 'night shift',
                                      'Japanese': '夜勤'}},
                 15: {'proper_noun': {'Chinese': '小夜',
                                      'German': 'Nachmittagsschicht',
                                      'English': 'evening shift',
                                      'Japanese': '準夜勤'},
                      'description': {'Chinese': '小夜',
                                      'German': 'Spätschicht',
                                      'English': 'evening shift',
                                      'Japanese': '準夜勤'}},
                 16: {'proper_noun': {'Chinese': '日班',
                                      'German': 'Tagschicht',
                                      'English': 'Day shift',
                                      'Japanese': '日勤'},
                      'description': {'Chinese': '日班',
                                      'German': 'Tagschicht',
                                      'English': 'Day shift',
                                      'Japanese': '日勤'}},
                 17: {'proper_noun': {'Chinese': '光罩',
                                      'German': 'Maske',
                                      'English': 'Mask',
                                      'Japanese': 'マスク'},
                      'description': {'Chinese': '光罩',
                                      'German': 'Photomaske',
                                      'English': 'Mask',
                                      'Japanese': 'フォトマスク'}},
                 18: {'proper_noun': {'Chinese': 'DP',
                                      'German': 'DP',
                                      'English': 'DP',
                                      'Japanese': 'DP'},
                      'description': {'Chinese': 'Data Platform，資料收集平台，收集各種系統log並分析異常。',
                                      'German': 'Datenplattform: Eine Plattform zur Sammlung und Analyse von Systemlogs und Anomalien.',
                                      'English': 'Data Platform: A data collection platform that gathers system logs and analyzes anomalies.',
                                      'Japanese': 'データプラットフォーム: 各種システムログを収集し異常を分析するプラットフォームです。'}},
                 19: {'proper_noun': {'Chinese': 'SGP',
                                      'German': 'SGP',
                                      'English': 'SGP',
                                      'Japanese': 'SGP'},
                      'description': {'Chinese': 'Secure GenAI Platform，安全GenAI平台，提供安全的AI服務。',
                                      'German': 'Sicheres GenAI-Plattform: Bietet sichere KI-Dienste.',
                                      'English': 'Secure GenAI Platform: Provides secure AI services.',
                                      'Japanese': 'セキュアGenAIプラットフォーム: 安全なAIサービスを提供します。'}},
                 20: {'proper_noun': {'Chinese': 'ETP',
                                      'German': 'ETP',
                                      'English': 'ETP',
                                      'Japanese': 'ETP'},
                      'description': {'Chinese': 'Enterprise Translation Platform，翻譯整合平台，提供安全且即時的翻譯服務，包含會議紀錄及查詢等功能。',
                                      'German': 'Unternehmensübersetzungsplattform: Bietet sichere und sofortige Übersetzungsdienste, einschließlich Sitzungsprotokollen und Abfragen.',
                                      'English': 'Enterprise Translation Platform: An integrated translation platform offering secure, real-time translation services, including meeting transcriptions and queries.',
                                      'Japanese': 'エンタープライズ翻訳プラットフォーム: 安全でリアルタイムな翻訳サービスを提供し、会議記録やクエリ機能を含みます。'}},
                 21: {'proper_noun': {'Chinese': 'Cloud Run',
                                      'German': 'Cloud Run',
                                      'English': 'Cloud Run',
                                      'Japanese': 'Cloud Run'},
                      'description': {'Chinese': 'Cloud Run 是一個完全託管的平台，讓開發者可以運行容器化的應用程式。它支持自動擴展，根據流量需求動態調整資源，適合部署 HTTP 驅動的微服務。',
                                      'German': 'Cloud Run: Eine vollständig verwaltete Plattform zum Ausführen containerisierter Anwendungen. Sie unterstützt automatisches Skalieren und passt Ressourcen dynamisch an den Datenverkehr an, ideal für HTTP-gesteuerte Microservices.',
                                      'English': 'Cloud Run: A fully managed platform for running containerized applications, supporting automatic scaling and dynamic resource allocation based on traffic, ideal for deploying HTTP-driven microservices.',
                                      'Japanese': 'Cloud Run: 完全管理型プラットフォームで、開発者はコンテナ化されたアプリケーションを実行できます。トラフィックに応じて自動でスケーリングし、HTTP駆動のマイクロサービスのデプロイに適しています。'}},
                 22: {'proper_noun': {'Chinese': 'Cloud Function',
                                      'German': 'Cloud Function',
                                      'English': 'Cloud Function',
                                      'Japanese': 'Cloud Function'},
                      'description': {'Chinese': 'Cloud Function 是一種無伺服器的計算服務，允許開發者撰寫簡單的單一用途功能，並根據事件觸發自動執行，無需管理伺服器基礎設施。',
                                      'German': 'Cloud Function: Ein serverloser Computing-Dienst, der es Entwicklern ermöglicht, einfache, ereignisgesteuerte Funktionen ohne Serververwaltung zu schreiben.',
                                      'English': 'Cloud Function: A serverless compute service that lets developers write simple, single-purpose functions triggered by events, without managing server infrastructure.',
                                      'Japanese': 'Cloud Function: サーバーレスの計算サービスで、開発者は簡単な単一目的の関数をイベントに基づき自動で実行できます。サーバーインフラの管理は不要です。'}},
                 23: {'proper_noun': {'Chinese': 'BigQuery',
                                      'German': 'BigQuery',
                                      'English': 'BigQuery',
                                      'Japanese': 'BigQuery'},
                      'description': {'Chinese': 'BigQuery 是一個無伺服器的、超大規模的數據倉庫服務，提供快速 SQL 查詢能力，適合分析大規模數據集，支持即時分析。',
                                      'German': 'BigQuery: Ein serverloses, hochskalierbares Data-Warehouse, das schnelle SQL-Abfragen für die Analyse großer Datensätze und Echtzeitanalysen bietet.',
                                      'English': 'BigQuery: A serverless, highly scalable data warehouse service that offers fast SQL querying capabilities for analyzing large datasets, supporting real-time analytics.',
                                      'Japanese': 'BigQuery: サーバーレスの大規模データウェアハウスサービスで、迅速なSQLクエリが可能です。大規模データセットの分析に適しており、リアルタイム分析をサポートします。'}},
                 24: {'proper_noun': {'Chinese': 'Pub/Sub',
                                      'German': 'Pub/Sub',
                                      'English': 'Pub/Sub',
                                      'Japanese': 'Pub/Sub'},
                      'description': {'Chinese': ' Pub/Sub 是一種消息傳遞服務，允許應用程式之間進行可靠且可擴展的非同步通訊，支持事件驅動架構和流式數據處理。',
                                      'German': 'Pub/Sub: Ein Nachrichtendienst, der zuverlässige und skalierbare asynchrone Kommunikation zwischen Anwendungen ermöglicht, unterstützt ereignisgesteuerte Architekturen und Streaming-Datenverarbeitung.',
                                      'English': 'Pub/Sub: A messaging service that enables reliable and scalable asynchronous communication between applications, supporting event-driven architectures and streaming data processing.',
                                      'Japanese': 'Pub/Sub: メッセージ伝達サービスで、アプリケーション間での信頼性と拡張性のある非同期通信を可能にし、イベント駆動のアーキテクチャやストリーミングデータ処理をサポートします。'}},
                 25: {'proper_noun': {'Chinese': 'Cloud SQL',
                                      'German': 'Cloud SQL',
                                      'English': 'Cloud SQL',
                                      'Japanese': 'Cloud SQL'},
                      'description': {'Chinese': 'Cloud SQL 是一個完全託管的關聯式資料庫服務，支持 MySQL、PostgreSQL 和 SQL Server，可以輕鬆地配置、維護和管理資料庫。',
                                      'German': 'Cloud SQL: Ein vollständig verwalteter relationaler Datenbankdienst, der MySQL, PostgreSQL und SQL Server unterstützt und eine einfache Konfiguration, Wartung und Verwaltung ermöglicht.',
                                      'English': 'Cloud SQL: A fully managed relational database service supporting MySQL, PostgreSQL, and SQL Server, allowing easy configuration, maintenance, and management of databases.',
                                      'Japanese': 'Cloud SQL: 完全管理型のリレーショナルデータベースサービスで、MySQL、PostgreSQL、SQL Serverをサポートし、容易に設定、維持、管理が可能です。'}},
                 26: {'proper_noun': {'Chinese': 'Artifact Registry',
                                      'German': 'Artifact Registry',
                                      'English': 'Artifact Registry',
                                      'Japanese': 'Artifact Registry'},
                      'description': {'Chinese': 'Artifact Registry 是一個管理容器映像、包和其他工件的託管服務，提供安全的存儲和版本控制。',
                                      'German': 'Artifact Registry: Ein verwalteter Dienst zur Speicherung von Container-Images, Paketen und anderen Artefakten, der sichere Speicherung und Versionskontrolle bietet.',
                                      'English': 'Artifact Registry: A managed service for storing container images, packages, and other artifacts, providing secure storage and version control.',
                                      'Japanese': 'Artifact Registry: コンテナイメージやパッケージ、その他のアーティファクトを管理するサービスで、安全なストレージとバージョン管理を提供します。'}},
                 27: {'proper_noun': {'Chinese': 'Cloud Storage',
                                      'German': 'Cloud Storage',
                                      'English': 'Cloud Storage',
                                      'Japanese': 'Cloud Storage'},
                      'description': {'Chinese': 'Cloud Storage 是一個全球範圍的物件存儲系統，提供高可用性、持久性和安全性，適合存儲和檢索任何類型的數據。',
                                      'German': 'Cloud Storage: Ein globales Objektspeichersystem, das hohe Verfügbarkeit, Beständigkeit und Sicherheit bietet, ideal für die Speicherung und den Abruf beliebiger Datentypen.',
                                      'English': 'Cloud Storage: A globally distributed object storage system offering high availability, durability, and security, suitable for storing and retrieving any type of data.',
                                      'Japanese': 'Cloud Storage: グローバルなオブジェクトストレージシステムで、高可用性、耐久性、安全性を提供し、あらゆる種類のデータの保存と取得に適しています。'}},
                 28: {'proper_noun': {'Chinese': 'GKE',
                                      'German': 'GKE',
                                      'English': 'GKE',
                                      'Japanese': 'GKE'},
                      'description': {'Chinese': 'Google Kubernetes Engine，是一個託管的 Kubernetes 服務，提供簡化的 Kubernetes 群集管理，讓開發者輕鬆部署、管理和擴展容器化應用。',
                                      'German': 'Google Kubernetes Engine: Ein verwalteter Kubernetes-Dienst, der die Verwaltung von Kubernetes-Clustern vereinfacht und Entwicklern ermöglicht, containerisierte Anwendungen einfach bereitzustellen, zu verwalten und zu skalieren.',
                                      'English': 'Google Kubernetes Engine: A managed Kubernetes service offering simplified cluster management, enabling easy deployment, management, and scaling of containerized applications.',
                                      'Japanese': 'Google Kubernetes Engine: 管理されたKubernetesサービスで、Kubernetesクラスタの管理を簡素化し、コンテナ化されたアプリケーションのデプロイ、管理、スケーリングを容易にします。'}},
                 29: {'proper_noun': {'Chinese': 'Vertex AI',
                                      'German': 'Vertex AI',
                                      'English': 'Vertex AI',
                                      'Japanese': 'Vertex AI'},
                      'description': {'Chinese': 'Vertex AI 是一個統一的機器學習平台，提供從資料準備、訓練到部署的全套工具，支持自動化機器學習和自定義模型的開發。',
                                      'German': 'Vertex AI: Eine integrierte Plattform für maschinelles Lernen, die Werkzeuge für Datenvorbereitung, Training und Bereitstellung bietet, unterstützt automatisiertes maschinelles Lernen und die Entwicklung benutzerdefinierter Modelle.',
                                      'English': 'Vertex AI: An integrated machine learning platform offering a full set of tools for data preparation, training, and deployment, supporting automated machine learning and custom model development.',
                                      'Japanese': 'Vertex AI: 統合された機械学習プラットフォームで、データ準備、トレーニングからデプロイまでの全ツールを提供し、自動化された機械学習とカスタムモデルの開発をサポートします。'}}}

CHINESE_DICT = {}
GERMAN_DICT = {}
ENGLISH_DICT = {}
JAPANESE_DICT = {}
DESC_DICT = {}
ALL_PROPER_NOUNS = {}
# Populate each dictionary separately
for entry_id, data in combined_dict.items():
    DESC_DICT[entry_id] = {
        "description": data["description"].get("English", "")
    }
    CHINESE_DICT[entry_id] = {
        "proper_noun": data["proper_noun"].get("Chinese", ""),
    }
    GERMAN_DICT[entry_id] = {
        "proper_noun": data["proper_noun"].get("German", ""),
    }
    ENGLISH_DICT[entry_id] = {
        "proper_noun": data["proper_noun"].get("English", ""),
    }
    JAPANESE_DICT[entry_id] = {
        "proper_noun": data["proper_noun"].get("Japanese", ""),
    }
for entry_id in combined_dict.keys():
    ALL_PROPER_NOUNS[entry_id] = {
        "Chinese": combined_dict.get(entry_id, {}).get("proper_noun", {}).get("Chinese", ""),
        "German": combined_dict.get(entry_id, {}).get("proper_noun", {}).get("German", ""),
        "English": combined_dict.get(entry_id, {}).get("proper_noun", {}).get("English", ""),
        "Japanese": combined_dict.get(entry_id, {}).get("proper_noun", {}).get("Japanese", ""),
    }

if __name__ == "__main__":
    ipdb.set_trace()
